name = "cf-workers-prisma-test"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-05-13"
placement = { mode = "smart"}


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "734c9235ba3d44d98c1377b4bc2fb6d4"
localConnectionString = "postgresql://user:password@localhost:5432/database"